app/models/post.py
from app.extensions import db
from datetime import datetime, timedelta
from app.slug import HasSlug

class Post(db.Model, HasSlug):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    content = db.Column(db.Text)
    create_time = db.Column(db.DateTime, default=datetime.now())

    @property
    def is_new(self):
        return datetime.now() - self.create_time < timedelta(days=3)

    def __repr__(self):
        return f'<Post "{self.title}">'

app/forms/__init__.py
from flask import Blueprint

bp = Blueprint('forms', __name__)


from app.forms import routes

app/forms/feedback.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email

class Feedback(FlaskForm):
    login = StringField('Login', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    message = StringField('Message', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/forms/routes.py
from flask import render_template, redirect, url_for
from app.forms import bp
from app.forms.feedback import Feedback

@bp.route('/feedback', methods=['GET', 'POST'])
def feedback():
    form = Feedback()

    if form.validate_on_submit():
        print(form.data)
        return redirect(url_for('main.index'))

    return render_template('forms/feedback.html', form=form)

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5

from config import Config
from app.extensions import db

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap = Bootstrap5(app)

    # Initialize Flask extensions here
    db.init_app(app)

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.posts import bp as posts_bp
    app.register_blueprint(posts_bp, url_prefix='/posts')

    from app.forms import bp as form_bp
    app.register_blueprint(form_bp, url_prefix='/')

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/about')
def about():
    return render_template('about.html')

@bp.route('/contact')
def contact():
    return render_template('contact.html')

app/posts/__init__.py
from flask import Blueprint

bp = Blueprint('posts', __name__)


from app.posts import routes

app/posts/routes.py
from flask import render_template
from sqlalchemy import desc
from app.posts import bp
from app.models.post import Post

@bp.route('/')
def index():
    posts = Post.query.order_by(desc(Post.create_time)).all()
    return render_template('posts/index.html', posts=posts)

@bp.route('/<string:slug>')
def post(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    return render_template('posts/post.html', post=post)

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} This is About Us page {% endblock %}</h1></span>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <link rel="stylesheet" type= "text/css" href= "{{ url_for('static', filename='styles/style.css') }}">
    {{ bootstrap.load_css() }}
</head>
<body>
    <nav>
    <nav class="nav nav-pills flex-column flex-sm-row">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-newspaper center" viewBox="0 0 16 16">
            <path d="M0 2.5A1.5 1.5 0 0 1 1.5 1h11A1.5 1.5 0 0 1 14 2.5v10.528c0 .3-.05.654-.238.972h.738a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 1 1 0v9a1.5 1.5 0 0 1-1.5 1.5H1.497A1.497 1.497 0 0 1 0 13.5zM12 14c.37 0 .654-.211.853-.441.092-.106.147-.279.147-.531V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5v11c0 .278.223.5.497.5z"/>
            <path d="M2 3h10v2H2zm0 3h4v3H2zm0 4h4v1H2zm0 2h4v1H2zm5-6h2v1H7zm3 0h2v1h-2zM7 8h2v1H7zm3 0h2v1h-2zm-3 2h2v1H7zm3 0h2v1h-2zm-3 2h2v1H7zm3 0h2v1h-2z"/>
        </svg>
        <a class="flex-sm-fill text-sm-center nav-link" href="{{ url_for('main.index') }}">Home</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="{{ url_for('main.about') }}">About</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="{{ url_for('posts.index') }}">Posts</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="{{ url_for('forms.feedback') }}">Feedback</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="{{ url_for('main.contact') }}">Contact</a>
    </nav>
    <hr>
    <div class="content">
        {% block content %} {% endblock %}
    </div>
    {{ bootstrap.load_js() }}
</body>
</html>

app/templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} This is Contact page {% endblock %}</h1></span>
{% endblock %}

app/templates/forms/feedback.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
    {{ render_form(form) }}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} The Home Page of FlaskApp {% endblock %}</h1></span>
{% endblock %}

app/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Posts</h1>
        <ul class="list-group mt-3">
            {% for post in posts %}
                <li class="list-group-item">
                    <h2><a href="{{ url_for('posts.post', slug=post.slug) }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{ post.title }}</a></h2>
                    <p>{{ post.content }}</p>
                    <small>{{ post.create_time }}</small>
                    {% if post.is_new %}
                        <span class="badge bg-pill bg-dark">New</span>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

app/templates/posts/post.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ post.title }}</h1>
        <p>{{ post.content }}</p>
        <p>{{ post.slug }}</p>
        <small>Created on: {{ post.create_time }}</small>
        <br>
        <a href="{{ url_for('posts.index') }}" class="btn btn-primary mt-3">Back to Posts</a>
    </div>
{% endblock %}